#SPDX-License-Identifier: MIT-0
---
# defaults file for up-list-vm-esx1
# defaults/main.yml
# variables avec la plus faible priorit√©


esx1_hostname: "CHANGEMOI"
esx1_username: "CHANGEMOI"
esx1_password: "CHANGEMOI"
esx1_validate_certs: false



esx2_hostname: "CHANGEMOI"
esx2_username: "CHANGEMOI"
esx2_password: "CHANGEMOI"
esx2_validate_certs: false
